Week4
Heesu01/likelion12th-web-session3 pull request #2
Opened 2024-05-02 05:13 UTC by Heesu01

로그인 기능 추가
좋아요 클릭 버튼 기능 추가

2024-05-03 11:25 UTC, constantly-dev reviewed
과제 수고하셨습니다 :)

2024-05-03 11:25 UTC, constantly-dev commented on src/App.js
>      </div>
가장 바깥에 감싸는 div를 스타일링을 하신건가요? app.css에 따로 스타일이 없는 것 같아서, 만약 목적이 없는 div라면 fragment관련 리뷰를 참고해주세요!

2024-05-03 11:25 UTC, constantly-dev commented on src/components/Login.jsx
> +          </div>
현재는 서버와 연결을 안하고 데이터를 임시로 사용하기 때문에 상관 없지만, 서버에게 form data(id, password 등)를 넘겨주는 상황이라면 form태그로 감싸고 button 태그의 type이 'button'이 아닌 submit이 되고, onClick 대신 onSubmit이 되어야 합니다! 물론 지금은 상관 없지만,  이 부분 인지해주세요 :)

2024-05-03 11:25 UTC, constantly-dev commented on src/components/introduction.css
> +    font-weight: bold;
font-weight을 bold와 같은 키워드로도 지정을 하지만, 글꼴마다 이 weight을 숫자로도 많이 표현합니다! 이후에 피그마 등을 보고 직접 만들면서 학습을 하겠지만, 글꼴마다 지원 값이 다르니 bold, regular 등은 어떤 숫자를 많이 쓰는 지 구글 폰트에서 그 값을 한번 정도 찾아보세요. 아 그렇구나 정도로 충분합니다!
https://fonts.google.com/noto/specimen/Noto+Sans+KR?subset=korean&noto.script=Kore

2024-05-03 17:00 UTC, hyunyeee requested changes
페이지가 많아서 힘들었을 거 같은데 잘하셨네용
고생하셨습니다 ~~ (´▽ʃ♡ƪ)

2024-05-03 17:00 UTC, hyunyeee commented on src/components/user.info.js
이 파일은 있는데 사용 안하고 있네요 일부러 빼두신걸까요?
원래 이 값을 localStorage에 저장하고, 이 값을 get 하고 input value랑 비교해서 로그인 상태 판별하는 게 요구사항이었는데
임의로 수정해서 나머지 부분 정상 작동 하는 건 확인 했습니다
localStorage에 set하는 부분만 추가 부탁드릴게용  ~~

2024-05-07 07:39 UTC, hyunyeee approved these changes

2024-05-07 07:40 UTC, merged